server:
  port: 8003
  servlet:
    context-path: /user

spring:
  application:
    name: server-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka # 注册中心注册地址
  instance:
    instance-id: server-user-8003
